# Generated by Django 3.0.2 on 2020-03-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('sn', models.CharField(max_length=80)),
                ('idrc_ip', models.GenericIPAddressField()),
                ('host_ip', models.GenericIPAddressField()),
                ('cluster_tag', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=50, null=True)),
                ('disk', models.CharField(max_length=50, null=True)),
                ('dev_model', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=20)),
                ('desc', models.TextField(null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_hostname', models.CharField(max_length=100)),
                ('vm_intention', models.CharField(max_length=100, null=True)),
                ('vm_register', models.CharField(max_length=10, null=True)),
                ('vm_monitor', models.CharField(max_length=5, null=True)),
                ('vm_ip', models.GenericIPAddressField()),
                ('vlan_tag', models.CharField(max_length=30)),
                ('vlan_id', models.IntegerField()),
                ('vm_cpu', models.CharField(max_length=10)),
                ('vm_disk', models.CharField(max_length=10, null=True)),
                ('vm_memory', models.CharField(max_length=10)),
                ('vm_os', models.CharField(max_length=20)),
                ('vm_desc', models.TextField(null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.HostInfo')),
            ],
        ),
    ]
