# Generated by Django 3.0.2 on 2020-01-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('sn', models.CharField(max_length=80)),
                ('idrc_ip', models.GenericIPAddressField()),
                ('host_ip', models.GenericIPAddressField()),
                ('cluster_info', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=10)),
                ('memory', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('pub_data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_hostname', models.CharField(max_length=100)),
                ('vm_ip', models.GenericIPAddressField()),
                ('vlan_tag', models.CharField(max_length=30)),
                ('vlan_id', models.IntegerField()),
                ('cpu', models.CharField(max_length=10)),
                ('memory', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('pub_data', models.DateField(auto_now_add=True)),
                ('cluster_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.HostInfo')),
            ],
        ),
    ]
