# Generated by Django 3.0.2 on 2020-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_fileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_size',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='type',
            field=models.IntegerField(),
        ),
    ]
