# Generated by Django 3.0.2 on 2020-01-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20200107_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='cluster_info',
            new_name='cluster_tag',
        ),
        migrations.RenameField(
            model_name='vminfo',
            old_name='cluster_info',
            new_name='cluster_tag',
        ),
    ]
