# Generated by Django 3.0.2 on 2020-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_fileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='type',
            field=models.IntegerField(),
        ),
    ]
