# Generated by Django 3.0.2 on 2020-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20200316_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='file_size',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
