# Generated by Django 3.0.2 on 2020-01-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20200108_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vminfo',
            old_name='cluster_tag',
            new_name='host',
        ),
    ]
