# Generated by Django 3.0.2 on 2020-01-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200108_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='pub_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vminfo',
            name='pub_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
