# Generated by Django 3.0.2 on 2020-03-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20200314_1452'),
        ('admin', '0004_auto_20200316_1516'),
    ]

    operations = [
    ]
