# Generated by Django 3.0.2 on 2020-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_merge_20200316_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='cpu',
            new_name='cpu_total_rate',
        ),
        migrations.RenameField(
            model_name='hostinfo',
            old_name='disk',
            new_name='disk_total_size',
        ),
        migrations.RenameField(
            model_name='hostinfo',
            old_name='memory',
            new_name='memory_total_size',
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='buy_date',
            field=models.CharField(max_length=50, null=True, verbose_name='购买日期'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='cpu_nums',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='cpu_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='dc_name',
            field=models.CharField(max_length=50, null=True, verbose_name='机房名称'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='dev_status',
            field=models.IntegerField(default=0, verbose_name='设备状态'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='end_svc_date',
            field=models.CharField(max_length=50, null=True, verbose_name='过保时间'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='idrc_net_in',
            field=models.CharField(max_length=50, null=True, verbose_name='远程管理卡网络'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='intention',
            field=models.CharField(max_length=100, null=True, verbose_name='用途'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='memory_nums',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='memory_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='rack_num',
            field=models.CharField(max_length=10, null=True, verbose_name='机柜号'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='sd_nums',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='sd_size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='slot_num',
            field=models.CharField(max_length=50, null=True, verbose_name='槽位号'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='ssd_nums',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='ssd_size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='supply_contact_name',
            field=models.CharField(max_length=50, null=True, verbose_name='供应商联系人'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='supply_phone',
            field=models.IntegerField(default=0, verbose_name='供应商联系号码'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='svc_net_in',
            field=models.CharField(max_length=50, null=True, verbose_name='业务网络'),
        ),
    ]
