# Generated by Django 3.0.2 on 2020-01-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20200108_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='hostname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
