# Generated by Django 3.0.2 on 2020-01-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20200108_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='pub_data',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='vminfo',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
