# Generated by Django 3.0.2 on 2020-03-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20200324_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='supply_name',
            field=models.CharField(max_length=50, null=True, verbose_name='供应商名称'),
        ),
    ]
