# Generated by Django 3.0.2 on 2020-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_hostinfo_supply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='cpu_core',
            field=models.IntegerField(default=1),
        ),
    ]
