# Generated by Django 3.0.2 on 2020-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_auto_20200109_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='dev_model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='disk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vminfo',
            name='vm_disk',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='cpu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='memory',
            field=models.CharField(max_length=50),
        ),
    ]
