# Generated by Django 3.0.2 on 2020-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_auto_20200111_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vminfo',
            name='vm_desc',
            field=models.TextField(null=True),
        ),
    ]
