# Generated by Django 3.0.2 on 2020-03-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_hostinfo_raid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='disk_total_size',
            new_name='ssd_total_size',
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='sd_total_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
