# Generated by Django 3.0.2 on 2020-03-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0010_auto_20200324_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='idrc_ip',
            new_name='idrac_ip',
        ),
    ]
