# Generated by Django 3.0.2 on 2020-03-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_auto_20200325_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='idrc_net_in',
            new_name='idrac_net_in',
        ),
    ]
