# Generated by Django 3.0.2 on 2020-03-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_auto_20200325_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='集群名称')),
                ('tag', models.CharField(max_length=50, unique=True, verbose_name='集群标记')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
