# Generated by Django 3.0.2 on 2020-03-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0014_clusterinfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterinfo',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='是否激活'),
        ),
    ]
