# Generated by Django 3.0.2 on 2020-03-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0016_vminfo_vm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='memory_total_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='sd_size',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='sd_total_size',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssd_size',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssd_total_size',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='vminfo',
            name='vm_cpu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vminfo',
            name='vm_disk',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vminfo',
            name='vm_memory',
            field=models.FloatField(default=0),
        ),
    ]
