# Generated by Django 3.0.2 on 2020-03-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0017_auto_20200330_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='cpu_rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='cpu_total_rate',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='sd_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='sd_total_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssd_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssd_total_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vminfo',
            name='vm_cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vminfo',
            name='vm_disk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vminfo',
            name='vm_memory',
            field=models.IntegerField(default=0),
        ),
    ]
