# Generated by Django 3.0.2 on 2020-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0021_auto_20200330_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='cpu_core',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='cpu_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='cpu_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='cpu_total_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='memory_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='memory_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='memory_total_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='sd_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='sd_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='sd_total_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssd_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssd_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssd_total_size',
            field=models.FloatField(default=0),
        ),
    ]
