# Generated by Django 3.0.5 on 2020-04-20 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='集群名称')),
                ('tag', models.CharField(max_length=50, unique=True, verbose_name='集群标记')),
                ('is_active', models.IntegerField(default=0, verbose_name='是否激活')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('sn', models.CharField(max_length=80)),
                ('idrac_ip', models.GenericIPAddressField()),
                ('host_ip', models.GenericIPAddressField()),
                ('cluster_tag', models.CharField(max_length=20)),
                ('cpu_nums', models.IntegerField(default=0)),
                ('cpu_core', models.IntegerField(default=0)),
                ('cpu_rate', models.FloatField(default=0)),
                ('cpu_total_rate', models.FloatField(default=0)),
                ('sd_nums', models.IntegerField(default=0)),
                ('sd_size', models.FloatField(default=0)),
                ('sd_total_size', models.FloatField(default=0)),
                ('ssd_nums', models.IntegerField(default=0)),
                ('ssd_size', models.FloatField(default=0)),
                ('ssd_total_size', models.FloatField(default=0)),
                ('dev_model', models.CharField(max_length=50, null=True)),
                ('memory_nums', models.IntegerField(default=0)),
                ('memory_size', models.IntegerField(default=0)),
                ('memory_total_size', models.IntegerField(default=0)),
                ('os', models.CharField(max_length=20)),
                ('desc', models.TextField(null=True)),
                ('buy_date', models.CharField(max_length=50, null=True, verbose_name='购买日期')),
                ('end_svc_date', models.CharField(max_length=50, null=True, verbose_name='过保时间')),
                ('svc_net_in', models.CharField(max_length=50, null=True, verbose_name='业务网络')),
                ('idrac_net_in', models.CharField(max_length=50, null=True, verbose_name='远程管理卡网络')),
                ('supply_name', models.CharField(max_length=50, null=True, verbose_name='供应商名称')),
                ('supply_contact_name', models.CharField(max_length=50, null=True, verbose_name='供应商联系人')),
                ('supply_phone', models.IntegerField(default=0, verbose_name='供应商联系号码')),
                ('rack_num', models.CharField(max_length=10, null=True, verbose_name='机柜号')),
                ('slot_num', models.CharField(max_length=50, null=True, verbose_name='槽位号')),
                ('dc_name', models.CharField(max_length=50, null=True, verbose_name='机房名称')),
                ('intention', models.CharField(max_length=100, null=True, verbose_name='用途')),
                ('raid', models.CharField(max_length=50, null=True, verbose_name='raid')),
                ('dev_status', models.IntegerField(default=0, verbose_name='设备状态')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_hostname', models.CharField(max_length=100)),
                ('vm_intention', models.CharField(max_length=100, null=True)),
                ('vm_register', models.CharField(max_length=10, null=True)),
                ('vm_monitor', models.CharField(max_length=5, null=True)),
                ('vm_ip', models.GenericIPAddressField()),
                ('vlan_tag', models.CharField(max_length=30)),
                ('vlan_id', models.IntegerField()),
                ('vm_cpu', models.IntegerField(default=0)),
                ('vm_disk', models.IntegerField(default=0)),
                ('vm_memory', models.IntegerField(default=0)),
                ('vm_os', models.CharField(max_length=20)),
                ('vm_desc', models.TextField(null=True)),
                ('vm_status', models.IntegerField(default=0, verbose_name='虚拟机状态')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostInfo')),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('file_size', models.CharField(default=0, max_length=10, null=True)),
                ('real_path', models.CharField(max_length=200, null=True)),
                ('real_name', models.CharField(max_length=100, null=True)),
                ('file_type', models.CharField(max_length=5, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
