# Generated by Django 3.0.5 on 2020-05-07 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=80, verbose_name='故障说明')),
                ('type', models.CharField(max_length=20, verbose_name='故障类别')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_data', models.DateField(null=True, verbose_name='结束时间')),
                ('device', models.CharField(max_length=100, null=True, verbose_name='故障设备')),
                ('info', models.TextField(null=True)),
                ('reason', models.TextField(null=True)),
                ('resolv_method', models.TextField(null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='工作内容')),
                ('type', models.CharField(max_length=10, verbose_name='工作类别')),
                ('pub_date', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
