# Generated by Django 3.0.5 on 2020-05-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dailyreport_troublereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='troublereport',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
