# Generated by Django 3.0.5 on 2020-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200507_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troublereport',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
    ]
