# Generated by Django 3.0.5 on 2020-05-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200507_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WanNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=50)),
                ('gateway', models.CharField(max_length=20)),
                ('bandwidth', models.CharField(max_length=10)),
                ('rent', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('sn', models.CharField(max_length=50)),
                ('device_model', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='LanNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('gateway', models.CharField(max_length=20)),
                ('vlanid', models.IntegerField()),
                ('function', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Branch')),
            ],
        ),
    ]
