# Generated by Django 3.0.5 on 2020-05-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_branch_lannetworks_networkdevices_wannetworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='isenable',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='troublereport',
            name='prevent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='troublereport',
            name='repairer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
