# Generated by Django 3.0.5 on 2020-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200518_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='wannetworks',
            name='dns1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wannetworks',
            name='dns2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
