# Generated by Django 3.0.5 on 2020-06-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200518_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevices',
            name='port_num',
            field=models.IntegerField(default=8),
        ),
        migrations.CreateModel(
            name='PortDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('desc', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Branch')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NetworkDevices')),
            ],
        ),
    ]
