# Generated by Django 3.0.5 on 2020-06-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200615_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portdesc',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
