# Generated by Django 3.0.5 on 2020-06-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200615_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('camera_nums', models.IntegerField()),
                ('idle_channel', models.IntegerField()),
                ('hdd', models.IntegerField()),
                ('idle_slot', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('desc', models.TextField(null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=50)),
                ('desc', models.TextField(null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Monitor')),
            ],
        ),
    ]
