# Generated by Django 3.0.5 on 2020-06-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_monitor_monitoraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifname', models.CharField(max_length=100)),
                ('access', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostInfo')),
            ],
        ),
    ]
