# Generated by Django 3.0.5 on 2020-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_hostinterface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='supply_phone',
            field=models.CharField(default=0, max_length=20, verbose_name='供应商联系号码'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='svc_net_in',
            field=models.CharField(max_length=100, null=True, verbose_name='业务网络'),
        ),
    ]
