# Generated by Django 3.0.5 on 2020-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200711_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='type',
            field=models.IntegerField(choices=[(0, '文件夹'), (1, '文件')], default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='dev_status',
            field=models.IntegerField(choices=[(0, '开机'), (1, '关机')], default=0, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='vminfo',
            name='vm_status',
            field=models.IntegerField(choices=[(0, '开机'), (1, '关机')], default=0, verbose_name='虚拟机状态'),
        ),
    ]
