# Generated by Django 3.0.5 on 2020-09-16 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200813_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='cluster_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ClusterInfo', to_field='tag'),
        ),
    ]
