# Generated by Django 3.0.5 on 2020-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200916_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterinfo',
            name='is_virt',
            field=models.IntegerField(choices=[(0, '非虚拟化'), (1, '虚拟化')], default=0),
        ),
    ]
