# Generated by Django 3.0.5 on 2020-09-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_clusterinfo_is_virt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterinfo',
            name='is_virt',
            field=models.IntegerField(choices=[(0, '普通服务器'), (1, '虚拟化集群')], default=0),
        ),
    ]
