# Generated by Django 3.0.5 on 2020-11-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200813_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('access_type', models.CharField(max_length=10, verbose_name='connection type')),
                ('require_authorize_addr', models.TextField(verbose_name='all_authorize_address')),
                ('real_authorize_addr', models.TextField(verbose_name='real_authorize_address')),
                ('is_proxy', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('firewall_policy_name', models.CharField(max_length=50)),
                ('nat_src_addr_pool', models.TextField()),
                ('nat_dest_addr_pool', models.TextField()),
                ('int_behave_control_policy', models.TextField(verbose_name='internet_behave_policy_name')),
                ('int_behave_audit_policy', models.TextField()),
                ('global_ip', models.CharField(max_length=15)),
                ('service_leader', models.CharField(max_length=10)),
                ('user_ip_addr', models.TextField()),
                ('user_permission', models.TextField()),
                ('desc', models.TextField()),
                ('is_active', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
