# Generated by Django 3.0.5 on 2020-11-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_bankprivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankprivate',
            name='global_ip',
            field=models.TextField(),
        )
    ]
